sudo: required

language: go

services:
  - docker

env:
  - CLAIR-DB_REPO=arminc/clair-db POSTGRES_IMAGE=postgres:10.3-alpine CLAIR_LOCAL_SCAN_IMAGE=arminc/clair-local-scan:v2.0.1

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY_SERVER
  - docker pull $POSTGRES_IMAGE
  - docker pull $CLAIR_LOCAL_SCAN_IMAGE
  - docker run -d --name postgres -e 'PGDATA=/var/lib/postgresql/clair' -e POSTGRES_PASSWORD=password $POSTGRES_IMAGE
  - sleep 20
  - docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE
  
script:
  - ./check.sh clair

after_success:
  - docker stop clair
  - docker stop postgres
  - docker commit postgres $CLAIR-DB_REPO:$(date +%Y-%m-%d)
  - docker tag $CLAIR-DB_REPO:$(date +%Y-%m-%d) $CLAIR-DB_REPO:latest
  - docker images
  - docker push $CLAIR-DB_REPO:$(date +%Y-%m-%d)
  - docker push $CLAIR-DB_REPO:latest
